/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],
  docs: [
    'provenance-blockchain',
    {
      type: 'category',
      label: 'Ecosystem',
      className: 'section-heading',
      collapsible: false,
      items: [
        {
          type: 'category',
          label: 'Provenance Blockchain: Financial Services Blockchain',
          link: {
            type: 'doc',
            id: 'ecosystem/financial-services-blockchain/index',
          },
          items: [
            'ecosystem/financial-services-blockchain/token-economics',
            'ecosystem/financial-services-blockchain/distribution',
          ],
        },
        {
          type: 'category',
          label: 'Governance',
          link: {
            type: 'doc',
            id: 'ecosystem/governance/index',
          },
          items: [
            'ecosystem/governance/voting',
            'ecosystem/governance/software-upgrade-proposal',
          ],
        },
        'ecosystem/foundation',
        {
          type: 'category',
          label: 'Community',
          link: {
            type: 'doc',
            id: 'ecosystem/community/index',
          },
          items: [
            'ecosystem/community/participants',
            'ecosystem/community/validator',
            'ecosystem/community/delegator',
            'ecosystem/community/asset-originators',
          ],
        },
        {
          type: 'category',
          label: 'Funding Program',
          link: {
            type: 'doc',
            id: 'ecosystem/funding-program/index',
          },
          items: [
            'ecosystem/funding-program/core-infrastructure-details',
            'ecosystem/funding-program/grants-program-details',
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Blockchain',
      className: 'section-heading',
      collapsible: false,
      items: [
        {
          type: 'category',
          label: 'Introduction',
          link: {
            type: 'doc',
            id: 'blockchain/introduction/index',
          },
          items: [
            'blockchain/introduction/application-architecture',
            'blockchain/introduction/major-components',
          ],
        },
        {
          type: 'category',
          label: 'Basics',
          link: {
            type: 'generated-index',
            description:
              'Basic concepts provided by the Provenance Blockchain application-specific blockchain',
          },
          items: [
            'blockchain/basics/anatomy-of-a-provenance-application',
            'blockchain/basics/transaction-lifecycle',
            'blockchain/basics/query-lifecycle',
            'blockchain/basics/accounts',
            'blockchain/basics/stablecoin',
            'blockchain/basics/gas-and-fees',
          ],
        },
        {
          type: 'category',
          label: 'Installing Provenanced',
          link: {
            type: 'doc',
            id: 'blockchain/running-a-node/index',
          },
          items: [
            {
              type: 'category',
              label: 'Running a Node',
              link: {
                type: 'doc',
                id: 'blockchain/running-a-node/running-a-node-1/index',
              },
              items: [
                {
                  type: 'category',
                  label: 'Joining Testnet',
                  link: {
                    type: 'doc',
                    id: 'blockchain/running-a-node/running-a-node-1/join-provenance-testnet/index',
                  },
                  items: [
                    'blockchain/running-a-node/running-a-node-1/join-provenance-testnet/running-a-testnet-node-from-quicksync',
                  ],
                },
                'blockchain/running-a-node/running-a-node-1/become-a-validator',
                'blockchain/running-a-node/running-a-node-1/configure-a-sentry',
                'blockchain/running-a-node/running-a-node-1/running-a-mainnet-node',
              ],
            },
          ],
        },
        {
          type: 'category',
          label: 'Using Provenanced',
          link: {
            type: 'doc',
            id: 'blockchain/using-provenance/index',
          },
          items: [
            'blockchain/using-provenance/query-command',
            'blockchain/using-provenance/tx-command',
          ],
        },
        {
          type: 'category',
          label: 'Explorer',
          link: {
            type: 'doc',
            id: 'blockchain/explorer/index',
          },
          items: [
            {
              type: 'category',
              label: 'Walkthrough',
              link: {
                type: 'doc',
                id: 'blockchain/explorer/ui-walkthrough/index',
              },
              items: [
                {
                  type: 'category',
                  label: 'Dashboard',
                  link: {
                    type: 'doc',
                    id: 'blockchain/explorer/ui-walkthrough/dashboard/index',
                  },
                  items: [
                    'blockchain/explorer/ui-walkthrough/dashboard/blocks',
                  ],
                },
                {
                  type: 'category',
                  label: 'Staking (Validators)',
                  link: {
                    type: 'doc',
                    id: 'blockchain/explorer/ui-walkthrough/staking-validators/index',
                  },
                  items: [
                    'blockchain/explorer/ui-walkthrough/staking-validators/validator-details',
                  ],
                },
                'blockchain/explorer/ui-walkthrough/transactions',
                'blockchain/explorer/ui-walkthrough/assets',
                'blockchain/explorer/ui-walkthrough/governance',
                'blockchain/explorer/ui-walkthrough/account-address',
                {
                  type: 'category',
                  label: 'Forthcoming',
                  link: {
                    type: 'generated-index',
                  },
                  items: [
                    'blockchain/explorer/ui-walkthrough/forthcoming/params',
                    'blockchain/explorer/ui-walkthrough/forthcoming/ibc',
                    'blockchain/explorer/ui-walkthrough/forthcoming/nfts',
                    'blockchain/explorer/ui-walkthrough/forthcoming/blockchain-statistics',
                  ],
                },
              ],
            },
            'blockchain/explorer/wallet',
            {
              type: 'category',
              label: 'Explorer as a Service',
              link: {
                type: 'doc',
                id: 'blockchain/explorer/explorer-as-a-service/index',
              },
              items: ['blockchain/explorer/explorer-as-a-service/ingestion'],
            },
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Modules',
      className: 'section-heading',
      collapsible: false,
      items: [
        'modules/inherited-modules',
        'modules/metadata-module',
        'modules/marker-module',
        'modules/account',
        'modules/name-module',
        'modules/provwasm-smart-contracts',
      ],
    },
    {
      type: 'category',
      label: 'Contract Execution Environment',
      className: 'section-heading',
      collapsible: false,
      items: [
        {
          type: 'category',
          label: 'P8e Contract Execution Environment',
          link: {
            type: 'doc',
            id: 'p8e/overview/index',
          },
          items: [
            'p8e/overview/api',
            {
              type: 'category',
              label: 'Encrypted Object Store',
              link: {
                type: 'doc',
                id: 'p8e/overview/encrypted-object-store/index',
              },
              items: [
                'p8e/overview/encrypted-object-store/encryption-scheme',
                'p8e/overview/encrypted-object-store/dime-encryption-envelope-specification',
              ],
            },
          ],
        },
        {
          type: 'category',
          label: 'P8e Usage',
          items: [
            'p8e/p8e-usage/architecture',
            'p8e/p8e-usage/specifications',
            'p8e/p8e-usage/building-new-contracts',
            'p8e/p8e-usage/data-retrieval',
            'p8e/p8e-usage/cross-scope-contract-example',
            'p8e/p8e-usage/multi-contract-example',
            'p8e/p8e-usage/multi-step-contract-example',
            'p8e/p8e-usage/next-steps',
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Integrating',
      className: 'section-heading',
      collapsible: false,
      items: [
        {
          type: 'category',
          label: 'Integrating with p8e',
          link: {
            type: 'doc',
            id: 'integrating/integrating-with-p8e/index',
          },
          items: [
            {
              type: 'category',
              label: 'Lending Ecosystem',
              link: {
                type: 'doc',
                id: 'integrating/integrating-with-p8e/lending-ecosystem/index',
              },
              items: [
                'integrating/integrating-with-p8e/lending-ecosystem/life-cycle-of-a-loan',
                'integrating/integrating-with-p8e/lending-ecosystem/data-mapping',
              ],
            },
            {
              type: 'category',
              label: 'P8e Contract Execution Environment (p8e)',
              link: {
                type: 'doc',
                id: 'integrating/integrating-with-p8e/p8e-contract-execution-environment-p8e/index',
              },
              items: [
                {
                  type: 'category',
                  label: 'Deploying the Encrypted Object Store',
                  link: {
                    type: 'doc',
                    id: 'integrating/integrating-with-p8e/p8e-contract-execution-environment-p8e/deploying-the-encrypted-object-store/index',
                  },
                  items: [
                    'integrating/integrating-with-p8e/p8e-contract-execution-environment-p8e/deploying-the-encrypted-object-store/configuring-replication',
                  ],
                },
                {
                  type: 'category',
                  label: 'P8e Contracts',
                  link: {
                    type: 'doc',
                    id: 'integrating/integrating-with-p8e/p8e-contract-execution-environment-p8e/p8e-contracts/index',
                  },
                  items: [
                    'integrating/integrating-with-p8e/p8e-contract-execution-environment-p8e/p8e-contracts/example-loan-contracts',
                  ],
                },
                {
                  type: 'category',
                  label: 'Key Management',
                  link: {
                    type: 'doc',
                    id: 'integrating/integrating-with-p8e/p8e-contract-execution-environment-p8e/key-management/index',
                  },
                  items: [
                    'integrating/integrating-with-p8e/p8e-contract-execution-environment-p8e/key-management/permissioning-others',
                  ],
                },
                'integrating/integrating-with-p8e/p8e-contract-execution-environment-p8e/summary',
              ],
            },
            {
              type: 'category',
              label: 'p8e CEE API',
              link: {
                type: 'doc',
                id: 'integrating/integrating-with-p8e/loan-onboarding-service/index',
              },
              items: [
                {
                  type: 'category',
                  label: 'API Usage Guide',
                  link: {
                    type: 'doc',
                    id: 'integrating/integrating-with-p8e/loan-onboarding-service/api-usage-guide/index',
                  },
                  items: [
                    'integrating/integrating-with-p8e/loan-onboarding-service/api-usage-guide/loan-onboarding',
                    'integrating/integrating-with-p8e/loan-onboarding-service/api-usage-guide/validation-request',
                    'integrating/integrating-with-p8e/loan-onboarding-service/api-usage-guide/validation-response',
                    'integrating/integrating-with-p8e/loan-onboarding-service/api-usage-guide/error-handling',
                  ],
                },
                {
                  type: 'category',
                  label: 'API Specification',
                  link: {
                    type: 'doc',
                    id: 'integrating/integrating-with-p8e/loan-onboarding-service/api-specification/index',
                  },
                  items: [
                    'integrating/integrating-with-p8e/loan-onboarding-service/api-specification/configuration-endpoints',
                    {
                      type: 'category',
                      label: 'Object Store Endpoints',
                      link: {
                        type: 'doc',
                        id: 'integrating/integrating-with-p8e/loan-onboarding-service/api-specification/object-store-endpoints/index',
                      },
                      items: [
                        'integrating/integrating-with-p8e/loan-onboarding-service/api-specification/object-store-endpoints/store-object',
                        'integrating/integrating-with-p8e/loan-onboarding-service/api-specification/object-store-endpoints/retrieve-object',
                        'integrating/integrating-with-p8e/loan-onboarding-service/api-specification/object-store-endpoints/store-file',
                        'integrating/integrating-with-p8e/loan-onboarding-service/api-specification/object-store-endpoints/retrieve-file',
                      ],
                    },
                    'integrating/integrating-with-p8e/loan-onboarding-service/api-specification/p8e-endpoints',
                    {
                      type: 'category',
                      label: 'Contract Execution Endpoints',
                      link: {
                        type: 'doc',
                        id: 'integrating/integrating-with-p8e/loan-onboarding-service/api-specification/contract-execution-endpoints/index',
                      },
                      items: [
                        'integrating/integrating-with-p8e/loan-onboarding-service/api-specification/contract-execution-endpoints/execute-contract',
                        'integrating/integrating-with-p8e/loan-onboarding-service/api-specification/contract-execution-endpoints/approve-contract',
                      ],
                    },
                  ],
                },
              ],
            },
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Apps Built on Provenance Blockchain',
      className: 'section-heading',
      collapsible: false,
      items: [
        'provenance-applications/apps-powered-by-provenance',
        {
          type: 'category',
          label: 'Figure LOS',
          link: {
            type: 'doc',
            id: 'provenance-applications/loan-origination-system-los/index',
          },
          items: [
            'provenance-applications/loan-origination-system-los/assets',
            'provenance-applications/loan-origination-system-los/onboarding-contract',
            'provenance-applications/loan-origination-system-los/funding',
            {
              type: 'category',
              label: 'Validation',
              link: {
                type: 'doc',
                id: 'provenance-applications/loan-origination-system-los/loan-validation/index',
              },
              items: [
                'provenance-applications/loan-origination-system-los/loan-validation/3rd-party-digital-signatures',
              ],
            },
            'provenance-applications/loan-origination-system-los/loan-servicing',
            'provenance-applications/loan-origination-system-los/data-sharing-with-portfolio-manager',
          ],
        },
        'provenance-applications/evault',
      ],
    },
    {
      type: 'category',
      label: 'Contributing',
      className: 'section-heading',
      collapsible: false,
      items: [
        {
          type: 'category',
          label: 'ADR',
          link: {
            type: 'doc',
            id: 'contributing/adr/index',
          },
          items: [
            'contributing/adr/template',
            {
              type: 'category',
              label: '100 Blockchain Configuration and Concepts',
              link: {
                type: 'doc',
                id: 'contributing/adr/blockchain-configuration-and-concepts/index',
              },
              items: [
                'contributing/adr/blockchain-configuration-and-concepts/genesis-network-configuration',
                'contributing/adr/blockchain-configuration-and-concepts/hd-wallets-key-pairs-addresses',
                'contributing/adr/blockchain-configuration-and-concepts/markers-tokens-and-coins',
                'contributing/adr/blockchain-configuration-and-concepts/transaction-fees-and-gas',
              ],
            },
            {
              type: 'category',
              label: '200 Base Infrastructure',
              link: {
                type: 'doc',
                id: 'contributing/adr/base-infrastructure/index',
              },
              items: [
                'contributing/adr/base-infrastructure/name-service',
                'contributing/adr/base-infrastructure/account-metadata',
              ],
            },
            {
              type: 'category',
              label: '300 Core Concepts',
              link: {
                type: 'doc',
                id: 'contributing/adr/core-concepts/index',
              },
              items: [
                'contributing/adr/core-concepts/identity',
                'contributing/adr/core-concepts/hash',
              ],
            },
            {
              type: 'category',
              label: '400 Smart Contracts',
              link: {
                type: 'doc',
                id: 'contributing/adr/smart-contracts/index',
              },
              items: [
                'contributing/adr/smart-contracts/smart-contracts-1',
                'contributing/adr/smart-contracts/p8e-metadata',
                'contributing/adr/smart-contracts/p8e-specifications',
                'contributing/adr/smart-contracts/p8e-smart-contracts',
                'contributing/adr/smart-contracts/omnibus',
              ],
            },
            'contributing/adr/administration',
            'contributing/adr/governance',
            'contributing/adr/business-applications',
            'contributing/adr/system-migration',
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Whitepapers',
      className: 'section-heading',
      collapsible: false,
      items: [
        'whitepapers/loan-participation-on-provenance',
        'whitepapers/securitization-on-provenance',
        'whitepapers/blockchain-impact-on-credit-ratings',
        'whitepapers/investment-fund-services-on-provenance',
        'whitepapers/supply-chain-finance-on-provenance',
      ],
    },
    {
      type: 'category',
      label: 'Provenance Blockchain FAQ',
      className: 'section-heading',
      collapsible: false,
      items: [
        'faq/foundation-faq',
        'faq/grants-program-faq',
        'faq/ecosystem-faq',
        'faq/blockchain-faq',
        'faq/hash-utility-token-faq',
        'faq/validator-faq',
        'faq/delegator-faq',
        'faq/client-contract-execution-environment-faq',
        'faq/smart-contract-faq',
        'faq/transactions-faq',
      ],
    },
    {
      type: 'category',
      label: 'License',
      className: 'section-heading',
      collapsible: false,
      items: [
        {
          type: 'link',
          label: 'Apache 2.0',
          href: 'https://www.apache.org/licenses/LICENSE-2.0',
        },
      ],
    },
  ],
};

module.exports = sidebars;
